add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status$python]($style)$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[\\$](bold cyan)"

[directory]
truncation_length = 6
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
format = "\\([$branch]($style)\\) "
style = "italic purple"

[git_status]
format = '[$all_status]($style)'
style = "cyan"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked = "? "
modified = " "
stashed = ""
staged = ""
renamed = ""
deleted = ""
